apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: post-service:latest
        imagePullPolicy: Never  # <-- Add this line
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: NodePort
